TensorRT predictions
[10/25/2025-16:21:53] [TRT] [E] createInferRuntime: Error Code 6: API Usage Error (CUDA initialization failure with error: 35 In nvinfer1::rt::`anonymous-namespace'::checkCudaInstallation at runtime/dispatch/runtime.cpp:689)
[10/25/2025-16:21:53] [TRT] [E] [checkMacros.cpp::nvinfer1::catchCudaError::226] Error Code 1: Cuda Runtime (In nvinfer1::catchCudaError at common/dispatch/checkMacros.cpp:226)
Traceback (most recent call last):
  File "D:\Hackathons\Knighthacks\knighthacks-25\chess_detection\LiveChess2FEN\test_lc2fen.py", line 64, in <module>
    main_tensorrt()
  File "D:\Hackathons\Knighthacks\knighthacks-25\chess_detection\LiveChess2FEN\test_lc2fen.py", line 55, in main_tensorrt
    predict_board_trt(MODEL_PATH_TRT, IMG_SIZE_TRT, PRE_INPUT_TRT, test=True)
  File "D:\Hackathons\Knighthacks\knighthacks-25\chess_detection\LiveChess2FEN\lc2fen\predict_board.py", line 330, in predict_board_trt
    with open(model_path, "rb") as f, trt.Runtime(trt_logger) as runtime:
TypeError: pybind11::init(): factory function returned nullptr